### ISSUE TITLE
Correções: tabelas de combate

### ISSUE THREAD

**Issue by xerxeslins** [pedroleone/osr-srd#2]
Na página de "https://ose-srd.netlify.app/jogando-jogo/13-tabelas-combate"

Tem dois "e" seguidos, na parte do "Humanos Normais".

"...1 Dado de Vida **e e** tem seus próprios valores ..."

Na parte de "Jogadas de Ataque usando TAC0 (Regra Opcional)"

Tem um "fo" que eu acho que deveria ser um "do".

"... subtraindo-se a CA do alvo **fo** TAC0..."

**Comment by pedroleone** [comment]
Resolvido pelo PR#5
