### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Nerun** [pedroleone/osr-srd#4]
Olá pessoal,

Eu uso Linux. Pra instalar _npm_ e _nodejs_ no Debian e derivados é fácil:
```
sudo aptitude install npm nodejs
```
Meu problema é que não sei o que fazer pra abrir o "gatsby develop", já tentei "npm gatsby develop" e vários outros. Não tenho ideia mesmo, vocês sabem?

**Comment by BrunoAssis** [comment]
Após instalar o `npm` e o `nodejs`, vá na pasta do projeto e rode `npm install`.

Após isso, o `gatsby develop` deve funcionar.

Se ainda assim não funcionar, tente rodar `npm install -g gatsby` antes de `gatsby develop`.

**Comment by Nerun** [comment]
Desculpe a demora em dar um feedback, esqueci que tinha feito essa pergunta!

Muito obrigado pela resposta!

Não consegui, mas o caminho parece ser esse que você indicou mesmo:
- `sudo aptitude install npm nodejs`

Na pasta do projeto:
- `npm install`
- `sudo npm install -g gatsby`
- `gatsby develop`

Obtive muitos `WARN` e `ERR!` na instalação do gatsby. Então rodei o `npm install -g gatsby` com `sudo`, aí funcionou.

Porém, ao rodar `gatsby develop`, outro erro apareceu: 
```
Gatsby requires Node.js 12.13.0 or higher (you have v10.24.0).
Upgrade Node to the latest stable release: https://gatsby.dev/upgrading-node-js
```
Depois eu vejo se consigo atualizar o meu node. De qualquer forma o caminho é esse que você indicou.

Obrigado, abraços!

PS.: pode ser uma boa criar um README.LINUX ou algo assim.

**Comment by pedroleone** [comment]
Olá @Nerun! Eu dei uma verificada, tem binários para debian que permitem instalar usando o apt-get.

```bash
# Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs
```

Fonte: https://github.com/nodesource/distributions/blob/master/README.md
