### ISSUE TITLE
Monstros > Encontros nos Ermos

### ISSUE THREAD

**Issue by Nerun** [pedroleone/osr-srd#6]
Aqui acho que já dá pra tirar a bola vermelha e colocar um X vermelho. Vocês já colocaram o texto em inglês e tiraram o _lorem ipsum_.

O trabalho de vocês está bem adiantado, gostei de ver.

PS.: eu finalmente consegui rodar no Linux. Obrigado!

**Comment by pedroleone** [comment]
Valeu @Nerun, terminei de colocar o conteúdo que faltava. Era bem pouca coisa mesmo, já coloquei o X vermelho devido no que está faltando traduzir. Muito obrigado!
Fique à vontade para mandar pull request também, se desejar. De qualquer forma estes issues já são bem úteis.
